version: '3.7'

services: 
  elasticsearch:
    container_name: 'elasticsearch'
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.2'
    ports:
      - '9200:9200'
    restart: always
  postgres:
    container_name: 'postgres'
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'root'
    restart: always
  pgadmin:
    container_name: 'pgadmin'
    image: 'dpage/pgadmin4'
    ports:
      - '8080:8080'
    restart: always